version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
- package-ecosystem: npm
  directory: "/"
  open-pull-requests-limit: 1 # avoid merge conflicts
  schedule:
    interval: daily