changelog:
  categories:
    - title: "Features :star:"
      labels:
        - "feature :star:"

    - title: "Enhancements :arrow_up:"
      labels:
        - "enhancement :arrow_up:"

    - title: "Bugs :bug:"
      labels:
        - "bug :bug:"

    - title: Dependencies
      labels:
        - dependencies

    - title: Other
      labels:
        - "*"
